#pragma once
#include "ascendc/host_api/tiling/template_argument.h"

ASCENDC_TPL_ARGS_DECL(MhcExpand,
    ASCENDC_TPL_DATATYPE_DECL(DT_X, C_DT_FLOAT16, C_DT_BF16),
    ASCENDC_TPL_UINT_DECL(MODE, 4, ASCENDC_TPL_UI_LIST, 0, 1, 2, 3, 4, 7),
    ASCENDC_TPL_UINT_DECL(ROWS, 4, ASCENDC_TPL_UI_LIST, 0, 1, 2, 4, 8),
    ASCENDC_TPL_UINT_DECL(COLS, 16, ASCENDC_TPL_UI_LIST, 0, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096),
    ASCENDC_TPL_UINT_DECL(S_LOG2, 4, ASCENDC_TPL_UI_LIST, 0, 8, 9, 10, 11, 12),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16, C_DT_BF16),
        ASCENDC_TPL_UINT_SEL(MODE, ASCENDC_TPL_UI_LIST, 0, 1, 2),
        ASCENDC_TPL_UINT_SEL(ROWS, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(COLS, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(S_LOG2, ASCENDC_TPL_UI_LIST, 0),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16, C_DT_BF16),
        ASCENDC_TPL_UINT_SEL(MODE, ASCENDC_TPL_UI_LIST, 3, 4),
        ASCENDC_TPL_UINT_SEL(ROWS, ASCENDC_TPL_UI_LIST, 1, 2, 4, 8),
        ASCENDC_TPL_UINT_SEL(COLS, ASCENDC_TPL_UI_LIST, 16, 32, 64, 128, 256, 512, 1024),
        ASCENDC_TPL_UINT_SEL(S_LOG2, ASCENDC_TPL_UI_LIST, 0),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(DT_X, C_DT_FLOAT16, C_DT_BF16),
        ASCENDC_TPL_UINT_SEL(MODE, ASCENDC_TPL_UI_LIST, 7),
        ASCENDC_TPL_UINT_SEL(ROWS, ASCENDC_TPL_UI_LIST, 2, 4, 8),
        ASCENDC_TPL_UINT_SEL(COLS, ASCENDC_TPL_UI_LIST, 1024, 2048, 4096),
        ASCENDC_TPL_UINT_SEL(S_LOG2, ASCENDC_TPL_UI_LIST, 8, 9, 10, 11, 12),
    ),
);
